- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - ec2:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        key_name: aws-dev
        instance_type: t2.small
        image: ami-e31a6594
        wait: no
        group: epiconcept
        count: 1
        vpc_subnet_id: subnet-68a77031
        assign_public_ip: yes
        region: eu-west-1
        instance_tags:
            Role: Icinga2Master
            Name: Icinga2Master

    - ec2:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        key_name: aws-dev
        instance_type: t2.small
        image: ami-e31a6594
        wait: no
        group: epiconcept
        count: 1
        vpc_subnet_id: subnet-68a77031
        assign_public_ip: yes
        region: eu-west-1
        instance_tags:
            Role: Icinga2Satellite
            Name: Icinga2Satellite

    - ec2:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        key_name: aws-dev
        instance_type: t2.micro
        image: ami-e31a6594
        wait: no
        groups:
            - epiconcept
        count: 3
        vpc_subnet_id: subnet-68a77031
        assign_public_ip: yes
        region: eu-west-1
        instance_tags:
            Role: Icinga2Agent
            Name: Icinga2Agent
