- hosts: MonitoringServers

  roles:

    - role: icinga2
      icinga2_conf_global: |
        include "constants.conf"
        include "zones.conf"
        include <itl>
        include <plugins>
        include "features-enabled/*.conf"
        include_recursive "conf.d"
      check_commands:
        check_nrpe: |
          "-H", "$address$",
          "-c", "$remote_nrpe_command$",
      tags: icinga2


    - role: icinga2-web2
      icinga2_web2_db_pass: "CHANGEME"
      icinga2_ido_mysql_configuration: |
      library "db_ido_mysql"

      object IdoMysqlConnection "ido-mysql" {
        user = "{{ icinga2_web2_db_user }}"
        password = "{{ icinga2_web2_db_pass }}"
        host = "localhost"
        database = "{{ icinga2_web2_db }}"
      }
      tags: icinga2-web2

- hosts: MonitoringAgents

  roles:
    - role: snmpd
      snmpd_cfg_rocommunity: oxalide
      snmpd_cfg_syslocation: oxalide
      snmpd_cfg_syscontact: report@oxalide.com
      snmpd_ic2_checks:
        - {name: "uptime", oid: "1.3.6.1.2.1.1.3.0" }
        - {name: "cpu-load-1m", oid: "1.3.6.1.4.1.2021.10.1.3.1", warn: "{{ ansible_processor_vcpus * 2 + 1 }}", crit: "{{ ansible_processor_vcpus * 3 }}" }
        - {name: "cpu-load-5m", oid: "1.3.6.1.4.1.2021.10.1.3.2", warn: "{{ ansible_processor_vcpus + 1 }}", crit: "{{ ansible_processor_vcpus * 2  + 1 }}" }
        - {name: "cpu-load-15m", oid: "1.3.6.1.4.1.2021.10.1.3.3", warn: "{{ ansible_processor_vcpus }}", crit: "{{ ansible_processor_vcpus + 1 }}" }
        - {name: "cpu-time-%user", oid: "1.3.6.1.4.1.2021.11.9.0", warn: "95", crit: "99" }
        - {name: "cpu-time-%system", oid: "1.3.6.1.4.1.2021.11.10.0", warn: "95", crit: "99" }
        - {name: "swap-total", oid: "1.3.6.1.4.1.2021.4.3.0" }
        - {name: "swap-free", oid: "1.3.6.1.4.1.2021.4.4.0" }
        - {name: "mem-total", oid: "1.3.6.1.4.1.2021.4.5.0" }
        - {name: "mem-free", oid: "1.3.6.1.4.1.2021.4.6.0" }
        - {name: "fd-count", oid: "1.3.6.1.4.1.2021.42001.45.0", warn: "1024", crit: "4096" }
      tags: snmpd
